global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - jenkins-llm-alertmanager:9093

scrape_configs:
  - job_name: 'jenkins-llm-app'
    static_configs:
      - targets: ['host.docker.internal:5000', 'host.docker.internal:5001']
    metrics_path: '/metrics'
    scrape_interval: 30s
